# Generated by Django 4.2.16 on 2024-11-04 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog_author_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 11, 5, 1, 23, 8, 955793), verbose_name='Опубликована'),
        ),
    ]
