# Generated by Django 4.2.16 on 2024-11-05 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 11, 5, 18, 42, 54, 534198), verbose_name='Опубликована'),
        ),
    ]
