# Generated by Django 4.2.16 on 2024-11-06 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_comment_options_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 11, 6, 4, 48, 20, 495582), verbose_name='Опубликована'),
        ),
    ]
