# Generated by Django 4.2.16 on 2024-11-23 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 11, 23, 16, 34, 17, 628363), verbose_name='Опубликована'),
        ),
    ]
