# Generated by Django 4.2.16 on 2024-11-30 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 11, 30, 6, 49, 15, 491243), verbose_name='Опубликована'),
        ),
    ]
