# Generated by Django 4.2.16 on 2024-11-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='комментарий',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='оценка',
            field=models.IntegerField(),
        ),
    ]
